apiVersion: batch/v1
kind: Job
metadata:
  name: tke-auth-post-upgrade-check
  namespace: tke
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
  labels:
    app: tke-auth-post-upgrade-check
spec:
  template:
    metadata:
      labels:
        app: tke-auth-post-upgrade-check
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: "NoSchedule"
      containers:
        - name: kubectl
          image: "{{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}"
          imagePullPolicy: "{{ .Values.kubectl.image.imagePullPolicy}}"
          command: ['/bin/sh']
          args:
            - "-c"
            - |
              /bin/bash <<'EOF'
              #!/bin/bash
              check=true
              while [ $check = true ]
              do
                check=false
                if [ $check = false ] && [ $(kubectl get client -A 2>&1 | grep "error" | wc -l) -gt 0 ]; then
                  check=true
                  sleep 1
                fi
                if [ $check = false ] && [ $(kubectl get deployment tke-auth-api -n tke 2>&1 | grep Error | wc -l) -gt 0 ]; then
                  check=true
                  sleep 1
                fi 
                if [ $check = false ] && [ $(kubectl get deployment tke-auth-api -n tke -o jsonpath="{.spec.replicas}") -ne $(kubectl get deployment tke-auth-api -n tke -o jsonpath="{.status.updatedReplicas}") ]; then
                  check=true
                  sleep 1
                fi
                if [ $check = false ] && [ $(kubectl get deployment tke-auth-controller -n tke 2>&1 | grep Error | wc -l) -gt 0 ]; then
                  check=true
                  sleep 1
                fi 
                if [ $check = false ] && [ $(kubectl get deployment tke-auth-controller -n tke -o jsonpath="{.spec.replicas}") -ne $(kubectl get deployment tke-auth-controller -n tke -o jsonpath="{.status.updatedReplicas}") ]; then
                  check=true
                  sleep 1
                fi
              done
              EOF
      restartPolicy: OnFailure
