apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.auth.tkestack.io
  annotations:
    cert-manager.io/inject-ca-from: tke/tke-ca
spec:
  group: auth.tkestack.io
  groupPriorityMinimum: 1000
  service:
    name: tke-auth-api
    namespace: tke
    port: 443
  version: v1
  versionPriority: 5
