kind: ConfigMap
apiVersion: v1
metadata:
  name: tke-auth-controller
  namespace: tke
data:
  tke-auth-controller.toml: |
    [secure_serving]
    tls_cert_file = "/app/certs/server.crt"
    tls_private_key_file = "/app/certs/server.key"

    [client]

      [client.auth]
      api_server = "https://tke-auth-api"
      api_server_client_config = "/app/conf/tke-auth-config.yaml"

    [features]
      category_path = "/app/auth/category.json"
      policy_path = "/app/auth/policy.json"
      tenant_admin = "{{ .Values.controller.adminUsername }}"
      tenant_admin_secret = "{{ .Values.controller.adminPassword }}"

  tke-auth-config.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: tke
        cluster:
          certificate-authority: /app/certs/ca.crt
          server: https://tke-auth-api
    users:
      - name: admin-cert
        user:
          client-certificate: /app/certs/admin.crt
          client-key: /app/certs/admin.key
    current-context: tke
    contexts:
      - context:
          cluster: tke
          user: admin-cert
        name: tke
