api:
  labels:
    app: tke-auth-api
  annotations:
  selector:
    matchLabels:
      app: tke-auth-api
  podAnnotations:
  podLabels:
    app: tke-auth-api
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
        - matchExpressions:
          - key: node-role.kubernetes.io/master
            operator: Exists
  # tke-auth-api组件在node上的对外暴露端口，默认31138
  nodePort: 31138
  replicas: 2
  image:
    repository: tkestack/tke-auth-api-amd64
    tag: v1.9.0
    imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  enableAudit: 
  # auth的重定向访问地址，包括集群服务器ip地址（必填）、tke-gateway的域名（可选）、集群高可用的VIP地址（可选）和集群的公共可访问域名（可选）
  redirectHosts:
    - 172.18.0.2
  # tke集群的租户id，默认default
  tenantID: default
  # OIDC认证方式的secret，默认自动生成
  # oIDCClientSecret: 25EOZex3zmIj5glxvYfDBp79YIM
  # authentication用户名，默认为admin
  adminUsername: admin
controller:
  labels:
    app: tke-auth-controller
  annotations:
  selector:
    matchLabels:
      app: tke-auth-controller
  podAnnotations:
  podLabels:
    app: tke-auth-controller
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
        - matchExpressions:
          - key: node-role.kubernetes.io/master
            operator: Exists
  replicas: 2
  image:
    repository: tkestack/tke-auth-controller-amd64
    tag: v1.9.0
    imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  # tke集群的用户名，默认为admin
  adminUsername: admin
  # tke集群的密码，默认自动生成
  adminPassword: admin
etcd:
  host: https://etcd.kube-system:2379
certificate:
   # 100y
  caCertDuration: 876000h
  caCertRenewBefore: 875900h
  adminCertDuration: 876000h
  adminCertRenewBefore: 875900h
  webhookCertDuration: 876000h
  webhookCertRenewBefore: 875900h
  serverCertDuration: 876000h
  serverCertRenewBefore: 875900h
  mountPath: /etc/kubernetes/pki
  dnsNames:
  uris: 
  ipAddresses:
kubectl:
  image:
    repository: tkestack/kubectl
    tag: 1.22.7
    imagePullPolicy: IfNotPresent
hookJob:
  webhookUpdate:
    enable: false
    parallelism: 1
    completions: 1
    ttlSecondsAfterFinishe: 5
  