kind: Service
apiVersion: v1
metadata:
  name: tke-platform-api
  namespace: tke
  annotations:
    tke.prometheus.io/scrape: "true"
    prometheus.io/scheme: https
spec:
  selector:
    app: tke-platform-api
  ports:
    - protocol: TCP
      port: 443
      targetPort: 9443