kind: Service
apiVersion: v1
metadata:
  name: tke-gateway
  namespace: tke
  annotations:
    tke.prometheus.io/scrape: "true"
    prometheus.io/scheme: https
    prometheus.io/port: "9441"
spec:
  selector:
    app: tke-gateway
  type: NodePort
  ports:
    - name: http
      nodePort: 31180
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      nodePort: 31443
      port: 443
      protocol: TCP
      targetPort: 443