{{ if eq .Values.networkMode "underlay" }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cilium-router
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
      - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cilium-router
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cilium-router
subjects:
  - kind: ServiceAccount
    name: cilium-router
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cilium-router
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
{{ toYaml .Values.cilium.router.labels | indent 4 }}
  name: cilium-router
  namespace: kube-system
  {{- if .Values.cilium.router.annotations }}
  annotations:
{{ toYaml .Values.cilium.router.annotations | indent 4 }}
  {{- end }}
spec:
  selector:
{{ toYaml .Values.cilium.router.selector | indent 4 }}
  template:
    metadata:
      {{- if .Values.cilium.router.podAnnotations }}
      annotations:
{{ toYaml .Values.cilium.router.podAnnotations | indent 8 }}
      {{- end }}
      labels:
{{ toYaml .Values.cilium.router.podLabels | indent 8 }}
    spec:
      affinity:
{{ toYaml .Values.cilium.router.affinity | indent 8 }}
      containers:
        - args:
            - -iface=$(HOST_IP)
            - -node-name=$(NODE_NAME)
            - -cluster-ip-range={{ .Values.clusterCIDR }}
            - -network-mode=bgp
            - -bgp-restart-time=300
            - -bgp-keepalive-time=60
            - -cidr-getter=tke-annotation
          command:
            - /cilium-router
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
          image: "{{ .Values.cilium.router.image.repository }}:{{ .Values.cilium.router.image.tag }}"
          imagePullPolicy: "{{ .Values.cilium.router.image.imagePullPolicy }}"
          name: cilium-router
          resources:
            limits:
              cpu: {{ .Values.masq.resources.limits.cpu }}
              memory: {{ .Values.masq.resources.limits.memory }}
            requests:
              cpu: {{ .Values.masq.resources.requests.cpu }}
              memory: {{ .Values.masq.resources.requests.memory }}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: cilium-router
      serviceAccountName: cilium-router
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
{{ end }}
